# Generated by Django 4.2.25 on 2025-10-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the service in minutes.')),
                ('allow_full_payment', models.BooleanField(default=True)),
                ('allow_deposit_payment', models.BooleanField(default=True)),
                ('allow_pay_later', models.BooleanField(default=False)),
                ('providers', models.ManyToManyField(blank=True, help_text='Providers who can perform this service.', related_name='services', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
    ]
