# Generated by Django 4.2.25 on 2025-10-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_base_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Check this to feature the service on the homepage.'),
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional: A link to a TikTok, Instagram, or Google Drive video.'),
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text="e.g., 'Color', 'Length', 'Add-on'", max_length=100)),
                ('value', models.CharField(help_text="e.g., 'Black', '16 inches', 'Deep Conditioning'", max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=0, default=0, help_text='Added to the base price if this option is selected.', max_digits=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Option',
                'verbose_name_plural': 'Service Options',
                'ordering': ['group_name', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Images will be sorted by this number (0 is first).')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory'),
        ),
    ]
