# Generated by Django 4.2.25 on 2025-11-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicecategory_service_is_popular_service_video_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Women's Braids', 'Men's Braids'", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Parent Category',
                'verbose_name_plural': 'Parent Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['parent', 'name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='services.parentcategory'),
        ),
    ]
