# Generated by Django 4.2.25 on 2026-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_parentcategory_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='allow_deposit_payment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='allow_full_payment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='allow_pay_later',
        ),
        migrations.AddField(
            model_name='service',
            name='best_for_hair_types',
            field=models.CharField(blank=True, help_text="e.g., 'Medium Hair, Thick Hair'", max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='suitability_warning',
            field=models.TextField(blank=True, help_text="e.g., 'This hairstyle may place additional tension on very thin hair.'"),
        ),
        migrations.AddField(
            model_name='service',
            name='target_audience',
            field=models.CharField(choices=[('Adults', 'Adults (16+)'), ('Children', 'Children (8-15)'), ('Everyone', 'Everyone (8+)')], default='Adults', help_text='Defines the strict age policy for this service.', max_length=50),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(help_text="e.g., 'Women's Braids', 'Men's Braids', 'Children's Braids'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='additional_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Added to base price.', max_digits=8),
        ),
    ]
