# Generated by Django 4.2.25 on 2026-08-10 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_service_allow_deposit_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="discount_percentage",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0-100. Applied as a seasonal discount (bulk admin action).",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="serviceimage",
            name="linked_options",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select the option(s) this image represents (e.g., 'Black' + 'Waist Length').",
                related_name="images",
                to="services.serviceoption",
            ),
        ),
    ]
