# Generated by Django 4.2.25 on 2026-08-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_service_discount_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("best_for_hair_types", models.CharField(blank=True, max_length=255)),
                ("suitability_warning", models.TextField(blank=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service translation",
                "verbose_name_plural": "Service translations",
                "unique_together": {("service", "language")},
            },
        ),
        migrations.CreateModel(
            name="ServiceOptionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "service_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="services.serviceoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service option translation",
                "verbose_name_plural": "Service option translations",
                "unique_together": {("service_option", "language")},
            },
        ),
        migrations.CreateModel(
            name="ServiceCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service category translation",
                "verbose_name_plural": "Service category translations",
                "unique_together": {("service_category", "language")},
            },
        ),
        migrations.CreateModel(
            name="ParentCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="services.parentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent category translation",
                "verbose_name_plural": "Parent category translations",
                "unique_together": {("parent_category", "language")},
            },
        ),
    ]
