# Generated by Django 4.2.25 on 2026-08-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0008_seed_catalog_translations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentcategory",
            options={
                "ordering": ["pk"],
                "verbose_name": "Parent Category",
                "verbose_name_plural": "Parent Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["pk"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["parent", "pk"],
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceoption",
            options={
                "ordering": ["group_name", "pk"],
                "verbose_name": "Service Option",
                "verbose_name_plural": "Service Options",
            },
        ),
        migrations.RemoveField(
            model_name="parentcategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="service",
            name="best_for_hair_types",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="suitability_warning",
        ),
        migrations.RemoveField(
            model_name="service",
            name="title",
        ),
        migrations.RemoveField(
            model_name="servicecategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="serviceoption",
            name="value",
        ),
        migrations.AlterField(
            model_name="serviceoption",
            name="group_name",
            field=models.CharField(
                help_text="Internal grouping key (e.g., 'Color', 'Length'). Never shown to customers — set the display name per language in the translations below.",
                max_length=100,
            ),
        ),
    ]
