# Generated by Django 4.2.25 on 2025-10-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Authentic African Braiding in the Heart of Budapest', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='Experience timeless beauty and intricate designs, handcrafted with passion and tradition.')),
                ('hero_image', models.ImageField(blank=True, help_text='Upload the main background image for the homepage hero section.', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
