# Generated by Django 4.2.25 on 2025-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='salon_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='salon_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='salon_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Full URL to your Facebook page.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Full URL to your Instagram profile.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_tiktok',
            field=models.URLField(blank=True, help_text='Full URL to your TikTok profile.'),
        ),
    ]
