# Generated by Django 4.2.25 on 2026-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0002_siteconfiguration_salon_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="address_description",
            field=models.TextField(
                blank=True,
                help_text="Directions / landmark description to help customers find the salon.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="business_hours",
            field=models.TextField(
                blank=True,
                help_text="Operating hours. Plain text, e.g., 'Mon–Fri: 9:00–18:00, Sat: 10:00–16:00'.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="business_name",
            field=models.CharField(
                default="Afrikai Hajfonás",
                help_text="The salon's business name, shown in the header, footer, and emails.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="favicon",
            field=models.ImageField(
                blank=True,
                help_text="Favicon (browser tab icon). Recommended: 32×32 or 64×64 PNG/ICO.",
                null=True,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_maps_link",
            field=models.URLField(
                blank=True, help_text="Full Google Maps URL for the salon's location."
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Site logo. Recommended: transparent PNG, max height 48px.",
                null=True,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="Canonical website URL (used for SEO canonical tags and email links).",
            ),
        ),
    ]
