# Generated by Django 4.2.25 on 2026-08-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0005_phase7d_seed_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("request_received", "Request Received"),
                            ("verification_pending", "Payment Verification Pending"),
                            ("payment_verified", "Payment Verified"),
                            ("appointment_approved", "Appointment Approved"),
                            ("appointment_rejected", "Appointment Rejected"),
                            ("appointment_expired", "Appointment Expired"),
                            ("expiry_reminder", "Expiry Reminder"),
                            ("refund_notification", "Refund Notification"),
                        ],
                        help_text="Developer-controlled identifier. Adding new types requires code changes.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, no email will be sent for this type.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplateTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "body_text",
                    models.TextField(
                        help_text="Plain text body. Use {{ placeholders }}. No WYSIWYG — email plain text is the primary format."
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        help_text="Optional HTML body. Plain HTML textarea only (no WYSIWYG). Email HTML is fragile — use simple inline styles only.",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="site_config.emailtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email template translation",
                "verbose_name_plural": "Email template translations",
                "unique_together": {("template", "language")},
            },
        ),
    ]
