# Generated by Django 4.2.25 on 2026-08-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_service_discount_percentage_and_more"),
        ("site_config", "0007_phase7c_seed_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_site_url",
                    models.URLField(
                        blank=True,
                        help_text="Canonical site URL for SEO (e.g., https://afrikaihajfonas.hu).",
                    ),
                ),
                (
                    "og_image_default",
                    models.ImageField(
                        blank=True,
                        help_text="Default Open Graph image (1200x630px recommended).",
                        null=True,
                        upload_to="seo/",
                    ),
                ),
                (
                    "google_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console verification code (content attribute value).",
                        max_length=200,
                    ),
                ),
                (
                    "bing_verification",
                    models.CharField(
                        blank=True,
                        help_text="Bing Webmaster Tools verification code.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Global SEO",
                "verbose_name_plural": "Global SEO",
            },
        ),
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url_path",
                    models.CharField(
                        blank=True,
                        help_text="URL path for static pages (e.g., '/', '/about/', '/services/').",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.OneToOneField(
                        blank=True,
                        help_text="Service for dynamic service detail pages.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page SEO",
                "verbose_name_plural": "Page SEO",
            },
        ),
        migrations.CreateModel(
            name="PageSEOTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.TextField(blank=True)),
                (
                    "page_seo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="site_config.pageseo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page SEO translation",
                "verbose_name_plural": "Page SEO translations",
                "unique_together": {("page_seo", "language")},
            },
        ),
        migrations.CreateModel(
            name="GlobalSEOTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("default_meta_title", models.CharField(max_length=200)),
                ("default_meta_description", models.TextField()),
                ("default_og_title", models.CharField(blank=True, max_length=200)),
                ("default_og_description", models.TextField(blank=True)),
                (
                    "global_seo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="site_config.globalseo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global SEO translation",
                "verbose_name_plural": "Global SEO translations",
                "unique_together": {("global_seo", "language")},
            },
        ),
    ]
