# Generated by Django 4.2.25 on 2026-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0009_phase7e_seed_seo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pageseo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("service__isnull", True), ("url_path__isnull", False)),
                    models.Q(("service__isnull", False), ("url_path__isnull", True)),
                    _connector="OR",
                ),
                name="pageseo_exactly_one_target",
            ),
        ),
    ]
