# Generated by Django 4.2.25 on 2026-08-19 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0011_phase7d_about_mission_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ topic",
                "verbose_name_plural": "FAQ topics",
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional grouping. FAQs without a topic appear under 'General'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faqs",
                to="site_config.faqtopic",
            ),
        ),
        migrations.CreateModel(
            name="FAQTopicTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="site_config.faqtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ topic translation",
                "verbose_name_plural": "FAQ topic translations",
                "unique_together": {("topic", "language")},
            },
        ),
    ]
