# Generated by Django 4.2.25 on 2026-08-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0012_faq_topics"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfigurationTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="The salon's business name in this language.",
                        max_length=200,
                    ),
                ),
                ("hero_title", models.CharField(max_length=200)),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "site_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="site_config.siteconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site configuration translation",
                "verbose_name_plural": "Site configuration translations",
                "unique_together": {("site_configuration", "language")},
            },
        ),
    ]
