# Generated by Django 4.2.25 on 2026-08-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_config", "0014_seed_site_config_translations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="business_name",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="hero_title",
        ),
    ]
