# Generated by Django 4.2.25 on 2025-10-14 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_available', models.BooleanField(default=False, help_text='Check if this is a special opening, uncheck for a day off.')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Time Slot Override',
                'verbose_name_plural': 'Time Slot Overrides',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday, 1=Tuesday, ..., 6=Sunday', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Availability Rule',
                'verbose_name_plural': 'Availability Rules',
                'ordering': ['provider', 'day_of_week', 'start_time'],
            },
        ),
    ]
