# Generated by Django 4.2.25 on 2025-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_timeslotoverride_availabilityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='provider_images/'),
        ),
    ]
