# Generated by Django 4.2.25 on 2026-08-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_provider_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="bio_de",
            field=models.TextField(blank=True, default="", help_text="German bio."),
        ),
        migrations.AddField(
            model_name="provider",
            name="bio_en",
            field=models.TextField(blank=True, default="", help_text="English bio."),
        ),
        migrations.AlterField(
            model_name="provider",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Hungarian bio (base language)."
            ),
        ),
    ]
