# Generated by Django 4.2.25 on 2026-08-10 15:59

import apps.bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0003_provider_profile_image"),
        ("services", "0006_service_discount_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frozen historical snapshot of selected option IDs and values.",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_email", models.EmailField(max_length=254)),
                ("client_phone", models.CharField(max_length=30)),
                (
                    "client_age",
                    models.PositiveSmallIntegerField(
                        help_text="Client's age. Validated against service target_audience."
                    ),
                ),
                (
                    "hair_length",
                    models.CharField(
                        choices=[
                            ("ear", "Ear Length"),
                            ("chin", "Chin Length"),
                            ("neck", "Neck Length"),
                            ("shoulder", "Shoulder Length"),
                            ("armpit", "Armpit Length"),
                            ("bra_strap", "Bra Strap Length"),
                            ("mid_back", "Mid Back Length"),
                            ("waist", "Waist Length"),
                            ("hip", "Hip Length"),
                        ],
                        max_length=20,
                    ),
                ),
                ("photo_front", models.ImageField(upload_to="hair_photos/")),
                ("photo_side", models.ImageField(upload_to="hair_photos/")),
                ("photo_back", models.ImageField(upload_to="hair_photos/")),
                (
                    "deposit_amount",
                    models.PositiveIntegerField(
                        help_text="Calculated deposit amount in HUF (frozen at request time)."
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("revolut", "Revolut"),
                            ("wise", "Wise"),
                            ("transfergo", "TransferGo"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated. Format: AFH-XXXXXX",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "proof_of_payment",
                    models.ImageField(
                        help_text="Screenshot of the manual bank transfer.",
                        upload_to="payment_proofs/",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                ("target_date", models.DateField()),
                ("target_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "held_until",
                    models.DateTimeField(
                        default=apps.bookings.models._default_held_until,
                        help_text="Slot is held until this time. Auto-expires if admin doesn't act.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pending Verification"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes visible to the client on the Guest Lookup page.",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes — NOT shown to clients."
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to="providers.provider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_requests",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Request",
                "verbose_name_plural": "Appointment Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundQueue",
            fields=[],
            options={
                "verbose_name": "Refund Queue Item",
                "verbose_name_plural": "Refund Queue",
                "ordering": ["-created_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bookings.appointmentrequest",),
        ),
    ]
