# Generated by Django 4.2.25 on 2026-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentrequest",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("revolut", "Revolut"),
                    ("wise", "Wise"),
                    ("transfergo", "TransferGo"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentrequest",
            name="proof_of_payment",
            field=models.ImageField(
                blank=True,
                help_text="Screenshot of the manual bank transfer.",
                upload_to="payment_proofs/",
            ),
        ),
    ]
