# Generated by Django 4.2.25 on 2026-08-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_appointmentrequest_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentrequest",
            name="reminder_1h_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set True once the 1-hour-before-expiry reminder email has been sent.",
            ),
        ),
        migrations.AddField(
            model_name="appointmentrequest",
            name="reminder_2h_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set True once the 2-hour-before-expiry reminder email has been sent.",
            ),
        ),
    ]
