# Generated by Django 4.2.25 on 2026-08-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_phase7b_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetailfield",
            name="image_value",
            field=models.ImageField(
                blank=True,
                help_text="For image type fields (e.g., QR codes).",
                null=True,
                upload_to="payment_details/",
            ),
        ),
    ]
