# Generated by Django 4.2.25 on 2026-08-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_phase7b_fix_image_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethodTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="bookings.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment method translation",
                "verbose_name_plural": "Payment method translations",
                "unique_together": {("payment_method", "language")},
            },
        ),
        migrations.CreateModel(
            name="PaymentDetailFieldTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hu", "Magyar"),
                            ("en", "English"),
                            ("de", "Deutsch"),
                        ],
                        max_length=2,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "payment_detail_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="bookings.paymentdetailfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment detail field translation",
                "verbose_name_plural": "Payment detail field translations",
                "unique_together": {("payment_detail_field", "language")},
            },
        ),
    ]
