# Generated by Django 4.2.25 on 2026-08-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_seed_payment_translations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={"ordering": ["display_order", "pk"]},
        ),
        migrations.AlterUniqueTogether(
            name="paymentdetailfield",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="name",
        ),
        migrations.RemoveField(
            model_name="paymentdetailfield",
            name="label",
        ),
    ]
