# Generated by Django 4.2.25 on 2026-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_remove_single_language_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentrequest",
            name="hair_length",
            field=models.CharField(
                choices=[
                    ("ear", "Ear"),
                    ("chin", "Chin"),
                    ("neck", "Neck"),
                    ("shoulder", "Shoulder"),
                    ("armpit", "Armpit"),
                    ("bra_strap", "Bra Strap"),
                    ("mid_back", "Mid Back"),
                    ("waist", "Waist"),
                    ("hip", "Hip"),
                ],
                max_length=20,
            ),
        ),
    ]
